### ISSUE TITLE
unable to set AwbEnable control

### ISSUE THREAD

**Issue by smroid** [lit-robotics/libcamera-rs#36] opened 2024-06-08 23:21 UTC
I am able to set request controls such as AeEnable, ExposureTime, AnalogueGain. However, when I try to set AwbEnable (true or false), I get:

../include/libcamera/controls.h:152: T libcamera::ControlValue::get() const [with T = float; typename std::enable\
_if<((! libcamera::details::is_span<U>::value) && (! std::is_same<std::__cxx11::basic_string<char>, typename std::remov\
e_cv< <template-parameter-1-1> >::type>::value)), std::nullptr_t>::type <anonymous> = nullptr]: Assertion `type_ == det\
ails::control_type<std::remove_cv_t<T>>::value' failed.

Any suggestions?

**Comment by aaronyeeio** [comment] 2024-10-11 01:56
I have the same issue here. The case for me is that I can't set `FrameDurationLimits` and it throws the same error as above.

**Comment by aaronyeeio** [comment] 2024-10-11 01:59
I wonder if this is caused by that `libcamera` has updated to v0.3.0. But I checked the official API compatibility across v0.1.0 to v0.3.0 and it shows a 97% coverage. And `include/libcamera/controls.h` also remains the same on the line it throws.

**Comment by chemicstry** [comment] 2024-10-14 08:49
This is duplicate of #31. I will check what I can do about that issue.

**Closed by chemicstry** 2024-10-14 08:49 UTC
